name: Tagged v* Release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          # artifacts: "release.tar.gz,foo/*.txt"
          # bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
